# JobWizard Experience Configuration
# TRUTH POLICY: Only include actual, verifiable experience

experience:
  - company: "Company Name"
    title: "Senior Software Engineer"
    location: "Remote"
    start_date: "2022-01"
    end_date: "present"
    description: |
      Brief description of role and responsibilities.
    achievements:
      - "Achievement 1 with measurable impact"
      - "Achievement 2 with specific metrics"
      - "Achievement 3 highlighting technical skills"
    technologies:
      - Rails
      - React
      - PostgreSQL
      - Docker

  # - company: "Previous Company"
  #   title: "Software Engineer"
  #   ... add more as needed

education:
  - institution: "University Name"
    degree: "Bachelor of Science in Computer Science"
    graduation_year: "YYYY"
    gpa: "X.X"  # Optional
    honors: []   # Optional

certifications:
  # - name: "AWS Certified Developer"
  #   issuer: "Amazon Web Services"
  #   date: "YYYY-MM"
  #   credential_id: "ABC123"

projects:
  # Highlight 2-3 impressive side projects
  - name: "Project Name"
    url: "https://github.com/you/project"
    description: "Brief description"
    technologies:
      - Rails
      - React




