# JobWizard Profile Configuration
# TRUTH POLICY: Never fabricate experience, skills, or achievements
# This is your source-of-truth professional data

personal:
  name: "Your Name"
  email: "your.email@example.com"
  phone: "+1-555-0100"
  location: "Digital Nomad (US Citizen)"
  linkedin: "https://linkedin.com/in/yourprofile"
  github: "https://github.com/yourusername"
  website: "https://yourportfolio.com"

summary: |
  Senior Full-Stack Engineer with X years experience building scalable
  Rails + React applications. Passionate about clean code, TDD, and AI-assisted development.

skills:
  languages:
    - Ruby
    - JavaScript/TypeScript
    - SQL
    - HTML/CSS
  
  frameworks:
    - Ruby on Rails
    - React
    - Vite
    - RSpec
  
  tools:
    - Docker
    - PostgreSQL
    - Redis
    - Git/GitHub
    - Cursor/VS Code

  practices:
    - TDD/BDD
    - CI/CD
    - Agile/Scrum
    - Code Review
    - Pair Programming

preferences:
  remote_only: true
  willing_to_relocate: false
  visa_sponsorship_required: false
  citizenship: "US"
  availability: "Immediate"
  salary_range: "$XXX,000 - $XXX,000"
  benefits_required:
    - Health insurance
    - 401k matching
    - Unlimited PTO




